### ISSUE TITLE
Don't commit the node_modules directory

### ISSUE THREAD

**Issue by StanleyMasinde** [Annaliskirwa/experimentingWithNode#1]
## About node_modules
The node_modules directory contains reusable models that are stored on [npmjs](https://npmjs.com) and sometimes they can get so big that they bloat your repository

## Solution
1. add a file called `.gitignore` in the file add this line `node_modules`
2. remove the node modules from git history with `git rm` node_modules
3. Commit and push

**Comment by Annaliskirwa** [comment]
Thankyou for the insight. I kept forgetting. let me work on it rn

**Comment by StanleyMasinde** [comment]
Awesome
